# Generated by Django 3.1.2 on 2021-01-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_userinformation'),
        ('core', '0005_lesson_is_walkthrough'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='code',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='incorrect_answers',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_concept',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='reference_set',
        ),
        migrations.RemoveField(
            model_name='lessonset',
            name='first_in_set',
        ),
        migrations.RemoveField(
            model_name='lessonset',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='mcchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='reasoning',
            name='mc_set',
        ),
        migrations.RemoveField(
            model_name='reasoning',
            name='reasoning_question',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='Concept',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='IncorrectAnswer',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonSet',
        ),
        migrations.DeleteModel(
            name='McChoice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Reasoning',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
