# Generated by Django 3.1.2 on 2021-02-13 18:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Item Name')),
                ('item_description', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='First Name')),
                ('retail_price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Retail Price (MSRP)')),
                ('is_available', models.BooleanField(default=False, verbose_name='Item is Available From Retail')),
                ('api_item_Id', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='API Link/Identifier')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Company Name')),
                ('company_phone_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(99999999999999)], verbose_name='Phone Number')),
                ('company_street_address', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Company Street Address')),
                ('company_city', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Company City')),
                ('company_state', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Company State')),
                ('company_zipcode', models.IntegerField(validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(99999)], verbose_name='Zip Code')),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('driver', 'Driver'), ('sponsor', 'Sponsor'), ('admin', 'Admin')], default='driver', max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Role Name')),
                ('first_name', models.CharField(default='N/A', max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='First Name')),
                ('last_name', models.CharField(default='N/A', max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Last Name')),
                ('phone_number', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(99999999999999)], verbose_name='Phone Number')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Last User Login')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='If User Verified Email')),
                ('is_active_account', models.BooleanField(default=True, verbose_name='If User Has Account Enabled')),
                ('approving_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinformation')),
                ('sponsor_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sponsorcompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorCatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Driver Point Value')),
                ('is_available_to_drivers', models.BooleanField(default=False, verbose_name='Is Item Available For Driver Redemption')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.catalogitem')),
                ('sponsor_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sponsorcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('inCart', 'In-Cart'), ('ordered', 'Ordered'), ('shipping', 'Shipping'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled'), ('returnRequest', 'Return In-Progress'), ('returned', 'Returned')], max_length=25, verbose_name='Order Status')),
                ('last_status_change', models.DateTimeField(verbose_name='Last DateTime of OrderStatus Update')),
                ('retail_at_order', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Retail Price (MSRP) at Order Time')),
                ('points_at_order', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Driver Point Cost at Order Time')),
                ('ordering_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinformation')),
                ('sponsor_catalog_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sponsorcatalogitem')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField(verbose_name='Static Image Link')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.catalogitem')),
            ],
        ),
        migrations.CreateModel(
            name='AuditPointChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(verbose_name='DateTime of Point Change')),
                ('point_change', models.IntegerField(verbose_name='Point Change for Driver')),
                ('change_reason', models.CharField(max_length=128, verbose_name='Point Change Reason')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userinformation')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(verbose_name='DateTime of login attempt')),
                ('is_successful', models.BooleanField(null=True, verbose_name='Whether a login attempt is successful')),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userinformation')),
            ],
        ),
        migrations.CreateModel(
            name='AuditApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(verbose_name='DateTime of Application Submission')),
                ('apply_status', models.CharField(choices=[('pending', 'Pending Approval'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=25, verbose_name='Application Status')),
                ('reject_reason', models.CharField(blank=True, max_length=128, verbose_name='Rejection Reason')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditapplication_driver', to='accounts.userinformation')),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditapplication_sponsor', to='accounts.userinformation')),
                ('sponsor_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sponsorcompany')),
            ],
        ),
    ]
