# Generated by Django 3.1.2 on 2021-03-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitemimage',
            name='catalog_item',
        ),
        migrations.RemoveField(
            model_name='sponsorcatalogitem',
            name='catalog_item',
        ),
        migrations.RemoveField(
            model_name='sponsorcatalogitem',
            name='sponsor_company',
        ),
    ]
