# Generated by Django 3.1.2 on 2021-03-04 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sponsor_catalog_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.sponsorcatalogitem'),
        ),
        migrations.AddField(
            model_name='auditpointchange',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userinformation'),
        ),
        migrations.AddField(
            model_name='auditloginattempt',
            name='login_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userinformation'),
        ),
        migrations.AddField(
            model_name='auditapplication',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditapplication_driver', to='accounts.userinformation'),
        ),
        migrations.AddField(
            model_name='auditapplication',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditapplication_sponsor', to='accounts.userinformation'),
        ),
        migrations.AddField(
            model_name='auditapplication',
            name='sponsor_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sponsorcompany'),
        ),
    ]
