# Generated by Django 3.1.2 on 2021-01-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
