# Generated by Django 3.1.2 on 2021-02-10 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210209_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditloginattempt',
            name='is_successful',
            field=models.BooleanField(null=True, verbose_name='Whether a login attempt is successful'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Last User Login'),
        ),
    ]
