# Generated by Django 3.1.2 on 2021-02-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210217_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='sponsor_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sponsorcompany'),
        ),
    ]
