# Generated by Django 3.1.2 on 2021-02-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210216_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorcompany',
            name='company_about_info',
            field=models.CharField(default='Enter about me info here', max_length=1000000, verbose_name='About sponsor'),
        ),
    ]
