# Generated by Django 3.1.2 on 2021-02-15 17:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210211_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='retail_price',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='DateTime of Last Update to Item'),
        ),
        migrations.AddField(
            model_name='sponsorcatalogitem',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='DateTime of Last Update to Item'),
        ),
        migrations.AlterField(
            model_name='auditpointchange',
            name='change_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='DateTime of Point Change'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='api_item_Id',
            field=models.CharField(max_length=256, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='API Link/Identifier'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='item_description',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='item_name',
            field=models.CharField(max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_status_change',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Last DateTime of OrderStatus Update'),
        ),
    ]
