# Generated by Django 3.1.2 on 2021-02-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210222_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditapplication',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditapplication_sponsor', to='accounts.userinformation'),
        ),
    ]
