# Generated by Django 3.1.2 on 2021-02-23 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20210223_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='approving_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userinformation'),
        ),
    ]
