# Generated by Django 3.1.2 on 2021-03-04 20:35

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20210304_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Item Name')),
                ('item_description', models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Item Description')),
                ('retail_price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Retail Price (MSRP)')),
                ('is_available', models.BooleanField(default=False, verbose_name='Item is Available From Retail')),
                ('last_modified', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Epoch time of Last Update to Item')),
                ('api_item_Id', models.CharField(max_length=256, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='API Link/Identifier')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorCatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Driver Point Value')),
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='DateTime of Last Update to Item')),
                ('is_available_to_drivers', models.BooleanField(default=False, verbose_name='Is Item Available For Driver Redemption')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogitem')),
                ('sponsor_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sponsorcompany')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField(verbose_name='Static Image Link')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.catalogitem')),
            ],
        ),
    ]
